### ISSUE TITLE
IO loading

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#1]
- TODO:  Felipe+Yves+Vladimir consolidate code and discuss what next steps could be
(done) - IO load data: please provide the scripts and some toy example
   - collect all in a subfolder in box (link provided on Google Drive)

**Comment by golipe** [comment]
wget http://homes.esat.kuleuven.be/~jsimm/chembl-IC50-346targets.mm
wget http://homes.esat.kuleuven.be/~jsimm/chembl-IC50-compound-feat.mm
wget http://homes.esat.kuleuven.be/~jsimm/chembl-IC50-compounds.csv
wget http://homes.esat.kuleuven.be/~jsimm/chembl-IC50-proteins-uniprot.csv

**Comment by golipe** [comment]
The data from my previous comment has been further processed. I have sent an email with the scripts and auxiliary data. Please use the data sent by e-mail in addition to this data:
https://drive.google.com/open?id=0B71wFMqxavy6Wl8zX19GaDB1VDg
for testing IO loading.
