### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by chupvl** [ExaScience/smurff#106]
Hello there.
I had a successful run of the SMURFF v0.9.2.
Then I installed 0.10 and had 'Segmentation fault (core dumped)'. 
Installation: conda based
Machine: Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz
I also tried to install boost via conda - did not helped. 
Also, if I do not limit number of threads - I got the same error message.

```
MP_NUM_THREADS=8 /home/vchupakh/excape/macau_excapeml_lite/run_smurff.py --matrix-dir /home/vchupakh/excape/macau_excapeml_lite/data_release --model-dest /home/vchupakh/excape/macau_excapeml_lite/data_release/results2/ --side c2v --affinity-level 6 --sample 1 --fold 1 --num-latent 128

Namespace(affinity=6, fold=1, matrix_dir='/home/vchupakh/excape/macau_excapeml_lite/data_release', model_dest='/home/vchupakh/excape/macau_excapeml_lite/data_release/results2/', nlv=128, sample=1, side='c2v')

Using OpenMP with up to 8 threads.
Segmentation fault (core dumped)

```

**Comment by tvandera** [comment]
Maybe add functionality to produce a stack trace automatically on segfault.

**Comment by chupvl** [comment]
Actually, MP_NUM_THREADS was not correctly picked up by run_smurff.py.
I put 8 threads, while it's running on 48. 

```
MP_NUM_THREADS=8 /home/vchupakh/excape/macau_excapeml_lite/run_smurff.py --matrix-dir /home/vchupakh/excape/macau_excapeml_lite/data_release --model-dest /home/vchupakh/excape/macau_excapeml_lite/data_release/results3/ --side c2v --affinity-level 6 --sample 1 --fold 1 --num-latent 128

Namespace(affinity=6, fold=1, matrix_dir='/home/vchupakh/excape/macau_excapeml_lite/data_release', model_dest='/home/vchupakh/excape/macau_excapeml_lite/data_release/results3/', nlv=128, sample=1, side='c2v')
Using OpenMP with up to 48 threads.
Segmentation fault (core dumped)

```

**Comment by chupvl** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x00000033c4c67974 in fwrite () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.3.x86_64

(gdb) bt
#0  0x00000033c4c67974 in fwrite () from /lib64/libc.so.6
#1  0x00007ffff16e21e5 in smurff::Session::init() ()
    at /usr/local/src/conda/smurff-0.10.2/lib/smurff-cpp/SmurffCpp/Sessions/Session.cpp:95
#2  0x00007ffff16a5a07 in __pyx_pf_6smurff_6smurff ()
   from /home/vchupakh/miniconda3/envs/smurff_0_10_wrndusshgpu01/lib/python3.6/site-packages/smurff.cpython-36m-x86_64-linux-gnu.so
#3  0x00007ffff16aa46d in __pyx_pw_6smurff_7smurff(_object*, _object*, _object*) ()
   from /home/vchupakh/miniconda3/envs/smurff_0_10_wrndusshgpu01/lib/python3.6/site-packages/smurff.cpython-36m-x86_64-linux-gnu.so
#4  0x00007ffff7b8dded in _PyCFunction_FastCallDict (func_obj=0x7fffe102b2d0, args=0x63ce38, nargs=Unhandled dwarf expression opcode 0xf3
)
    at Objects/methodobject.c:231
#5  0x00007ffff7b8e046 in _PyCFunction_FastCallKeywords (func=0x7fffe102b2d0, stack=0x63ce38, nargs=1, kwnames=Unhandled dwarf expression opcode 0xf3
)
    at Objects/methodobject.c:294
#6  0x00007ffff7c2703a in call_function (pp_stack=0x7fffffffc090, oparg=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:4824
#7  0x00007ffff7c2b438 in _PyEval_EvalFrameDefault (f=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:3338
#8  0x00007ffff7c26c3e in _PyEval_EvalCodeWithName (_co=0x7ffff1b38ae0, globals=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:4153
#9  0x00007ffff7c2726d in PyEval_EvalCodeEx (_co=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:4174
#10 0x00007ffff7c272bb in PyEval_EvalCode (co=Unhandled dwarf expression opcode 0xf3
) at Python/ceval.c:730
#11 0x00007ffff7c62132 in run_mod (fp=Unhandled dwarf expression opcode 0xf3
) at Python/pythonrun.c:1025
#12 PyRun_FileExFlags (fp=Unhandled dwarf expression opcode 0xf3
) at Python/pythonrun.c:978
#13 0x00007ffff7c62297 in PyRun_SimpleFileExFlags (fp=0x63ccd0, filename=<value optimized out>, closeit=1,
    flags=0x7fffffffc390) at Python/pythonrun.c:420
#14 0x00007ffff7c7e39d in run_file (argc=Unhandled dwarf expression opcode 0xf3
) at Modules/main.c:338
#15 Py_Main (argc=Unhandled dwarf expression opcode 0xf3
) at Modules/main.c:809
#16 0x0000000000400bbc in main (argc=16, argv=Unhandled dwarf expression opcode 0xf3
) at ./Programs/python.c:69
(gdb)

**Comment by tvandera** [comment]
opening the csv status file for writing fails, but we do not check this and blindly continue

**Comment by chupvl** [comment]
Felipe fixed it!

**Comment by tvandera** [comment]
Since a40a4cbc6f66a2a03c84fa80c0a3dbc6626e50d3, we now also check if we can open files for writing.
