### ISSUE TITLE
Errors in example (documentation)

### ISSUE THREAD

**Issue by jaak-s** [ExaScience/smurff#117]
Few examples are incorrect on this page:
  https://smurff.readthedocs.io/en/latest/notebooks/different_noise_models.html

The examples of "Adaptive noise", "Binary matrices" get in `Y` parameter, which is not supported, should be `Ytrain`. Also `aux_data` should be removed, it is not supported anymore, right? The line numbers in the text of "Binary matrices" are off:
> Care has to be taken to make input to the model, as operating with sparse matrices can drop real 0 measurements. In the below example, we first copy the matrix (line 9) and then threshold the data to binary (line 10).

Also "Tensor Factorization" example has `aux_data` argument.

**Comment by tvandera** [comment]
Thanks for reporting this. Indeed, those examples are quite outdated. I'll fix them. Tom

**Comment by tvandera** [comment]
Docs fixed:

https://smurff.readthedocs.io/en/latest/notebooks/different_noise_models.html

Please use smurff-0.14, as 0.13.x contains a bug in the ProbitNoise.
