### ISSUE TITLE
Misnamed file path on Windows

### ISSUE THREAD

**Issue by tangoed2whiskey** [ExaScience/smurff#121]
Hi,

I've just updated to version 0.14..2 on conda on Windows, and my basic test script no longer works, with the assertion error
`assert: Error opening file: C:\{file system}\smurff\test/save/root.ini`
i.e. the /save directory have used a forward slash rather than the backward slash Windows needs? 

A fix would be great, I was hoping to try out the improved OOM predictions!

**Comment by tvandera** [comment]
Hey Tom,

My windows version happily accepts a mix of \ and / in path names.

My guess is that the directory `C:\{file system}\smurff\test/save/` does not exit.

Could this be?
Tom

**Comment by tangoed2whiskey** [comment]
Hi,
That is correct: I was using `save_prefix="test/save"` in the MacauSession, and in previous versions this had created files like `test/save-root.ini`, whereas now it failed.  Using `save_prefix="test/save/"` now works.  So just a formatting issue on file names I think.
