### ISSUE TITLE
pip support for Python API

### ISSUE THREAD

**Issue by BhuvaneshBhatt** [ExaScience/smurff#122]
Could you please add support for installing the Python API for SMURFF via pip?

**Comment by tvandera** [comment]
Yes, but this will take some time. Is this critical for you?

**Comment by BhuvaneshBhatt** [comment]
> Yes, but this will take some time. Is this critical for you?

Not in the least. I'm just interested in trying it out; I'm not using it for a project (yet).

**Comment by olivierjeunen** [comment]
I would also appreciate support for pip, if at all possible.
I've noticed that the library installation via `pip install smurff` works, but importing it later on gives me the following error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/ojeunen/.local/lib/python3.6/site-packages/smurff/__init__.py", line 1, in <module>
>     from .smurff import *
>   File "/home/ojeunen/.local/lib/python3.6/site-packages/smurff/smurff.py", line 1, in <module>
>     from .wrapper import TrainSession
> ModuleNotFoundError: No module named 'smurff.wrapper'

**Comment by tvandera** [comment]
Hi all, I just looked into adding support for Python wheels, and things are complicated:

https://packaging.python.org/guides/installing-scientific-packages/

Is there any reason you cannot use conda?

**Comment by tvandera** [comment]
Hi, I've made a set of packages for Linux and MacOS. They still have to be tested further, but I'd be happy if some if you could test them out.

**Comment by suchow** [comment]
@tvandera Happy to help with testing on macOS 10.15.

**Comment by tvandera** [comment]
@suchow Cool, can you try 
- `pip install smurff` (using python 3.5/3.6/3.7 or 3.8)
- `import smurff` as a first test
- next you can try to run `python -m unittest` in [`python/smurff/test`](https://github.com/ExaScience/smurff/tree/release-0.15/python/smurff/test). Make sure to checkout the correct branch from GitHub (`release-0.15`).

**Comment by suchow** [comment]
@tvandera 

Both worked.

Log showing a successful install using pip on macOS 10.15 and Python 3.7.7: https://gist.github.com/suchow/e3729e9949f8e33f00503d0395cffeb6

And then:
```
(smurff) (base) ➜  test git:(release-0.15) python3 -m unittest
.....................................................................................................
----------------------------------------------------------------------
Ran 101 tests in 3.131s

OK
```

**Comment by tvandera** [comment]
Starting from v0.16.0, there are now official pip packages for smurff on linux and macOS: https://pypi.org/project/smurff
