### ISSUE TITLE
PredictSessions give error with > 2 modes

### ISSUE THREAD

**Issue by suchow** [ExaScience/smurff#126]
PredictSession's `__init__` method asserts that the number of modes is 2. Does this imply that these sessions cannot be used for tensor factorization?

https://github.com/ExaScience/smurff/blob/2bb64fc443abf895e593710ef5d91a9864189583/python/smurff/smurff/predict.py#L175

**Comment by tvandera** [comment]
Indeed, that is a know limitation, that can easily be fixed. I'll adapt the code.

**Comment by tvandera** [comment]
Adapted the code, seems to work. All test pass. I'll make a release after some further testing.

**Comment by tvandera** [comment]
SMURFF v0.16.0 released. Conda and pip packages available.
