### ISSUE TITLE
Does SMURFF implement a subset of Macau?

### ISSUE THREAD

**Issue by suchow** [ExaScience/smurff#127]
My understanding from the [original Macau paper](https://arxiv.org/pdf/1509.04610.pdf) is that the algorithm is defined over a hypergraph of nodes and relations, jointly factorizing the tensors and producing a single set of latents for each entity. However, SMURFF appears to allow only two or three entities, factoring a single matrix or tensor (plus side-information for each entity).

Is it possible, for example, to use SMURFF to jointly factor a model with several entities and relations between them?

**Comment by tvandera** [comment]
Hi Jordan,

ExaScience/smurff and jaak-s/macau are fast, but only support tensor/matrix factorization with optional side info.

The julia implementation of Macau (https://github.com/jaak-s/BayesianDataFusion.jl) supports multi-relation factorization.

**Comment by suchow** [comment]
Thanks!
