### ISSUE TITLE
prediction empty values

### ISSUE THREAD

**Issue by jordantkohn** [ExaScience/smurff#129]
Hello,

What's the best way to make predictions for **only** the empty values in the original dataframe?
I've found that predict_some() only returns predictions for cells that aren't empty.

My current method is to use predict_all() but then only extract the predictions in positions that are empty in the original input matrix. Is there a better way to do this?

Thank you

**Comment by tvandera** [comment]
Hello Jordan,

I think predict_all is currently your best option. If this is too slow, we can look at improving this.

Tom
