### ISSUE TITLE
installation of smurff with conda

### ISSUE THREAD

**Issue by fwmeng88** [ExaScience/smurff#130]
Thanks for building this interesting and useful package!

I am trying to use it for my research. However, I got some problems when trying to install it in the cluster. 

As the system is complaining the whl is not supported, I switched to conda. However, after installed with conda, I got an error with importing the package. I was using python 3.8.5.

```bash
>>> import smurff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'smurff'
```
I also tried with python=3.7.9 with conda, but it installed 0.14 version instead of 0.16 one.

Any suggestion would be apprecriated. Thank you! 
@tvandera

**Comment by tvandera** [comment]
I'll have a look!

**Comment by tvandera** [comment]
Hello @fwmeng88 

I've just tried on linux and MacOS, to install smurff=0.16 using conda, and it seems to work for me. 

Can you provide more details: the commands you issued, an error message, the system you used?

Thanks,
Tom

**Comment by fwmeng88** [comment]
Dear Tom. Sorry for the late reply. I used `conda install -c vanderaa smurff` to install the package in the cluster.

You can ignore the problem as I have figured a way of compiling smurff in the cluster. 
Tons of thanks. @tvandera

**Comment by tvandera** [comment]
I will also try on Centos 7.8.2003 and let you know.
If you can, can you send me your error from `conda install -c vanderaa smurff` on CentOS?

**Comment by fwmeng88** [comment]
There is no error information with `conda install -c vanderaa smurff`, but when I tried to import smurff, the error shows,

```python
>>> import smurff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'smurff'
```

Thanks for following up on the issuse.

**Comment by tvandera** [comment]
Did you activate the environment?

**Comment by fwmeng88** [comment]
Yes. I activated my virtual environment before using `conda` to install `smurff`.
