### ISSUE TITLE
conda install version is 0.14.0

### ISSUE THREAD

**Issue by victorconan** [ExaScience/smurff#140]
It seems using conda install, the version of smurff is 0.14.0. That version seems not supporting the inference on the tensor since the code is checking mode =2 in `smurff/predict.py`:
```
assert self.nmodes == 2
```
I saw in the latest code, this has been resolved. Is there any easy way to install the latest version from conda?
Thanks!

**Comment by victorconan** [comment]
Seems using `pip install smurff` solves the problem!

**Comment by tvandera** [comment]
This was a conda issue. I hope this has been solved now.
