### ISSUE TITLE
Prediction for tensor input

### ISSUE THREAD

**Issue by victorconan** [ExaScience/smurff#141]
Hi!

Is there any example of inferencing on tensors with side information? When I tried to input the indices as the below:

```
predictor.predict([0, 0, 0])
```
I got an array of size two:
```
[array([[[0.38417462]]]), array([[[0.14095366]]])]
```

Not sure how I could properly input tensors. Any help would be appreciated!

Thanks!

**Comment by victorconan** [comment]
My predict session prints as: 

```
PredictSession with 2 samples
  Data shape = (862, 661, 15)
  Beta shape = [29, 0, 0]
  Num latent = 32
```
I have side info as:
```
row_side_info =  csr_matrix(side_info.values).getrow(0)
<1x29 sparse matrix of type '<class 'numpy.longlong'>'
	with 6 stored elements in Compressed Sparse Row format>
```
But when I do `predictor.predict([0,0,0], row_side_info)`, I got error:
```
AssertionError: You should provide as many parameters as dimensions of the train matrix/tensor
```

**Comment by tvandera** [comment]
> My predict session prints as (not sure what 2 samples mean?):

SMURFF uses [Gibbs sampling](https://en.wikipedia.org/wiki/Gibbs_sampling) to build the posterior distribution. This is the number of samples of the [posterior distribution](https://en.wikipedia.org/wiki/Posterior_probability).

**Comment by tvandera** [comment]
> ```
> predictor.predict([0, 0, 0])
> ```

Assuming you are using SMURFF 0.17, the `[0,0,0]` will be interpreted as a single coordinate in the 3D tensor according to the docs  [here](https://smurff.readthedocs.io/en/release-0.17/api/inference.html#smurff.PredictSession.predict). 

Hence the function returns a single element numpy array for each sample.

**Comment by tvandera** [comment]
> But when I do `predictor.predict([0,0,0], row_side_info)`, I got error:

If you want to predict using sideinfo you should replace one the coordinates with sideinfo:
 `predictor.predict([row_side_info,0,0])`. The function expects all input (sideinfo or coordinates spec) to be in the first argument.

**Comment by victorconan** [comment]
Got it, thank you so much!
