### ISSUE TITLE
Add support for trunc normal 

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#15]
commit to be ported: 0a90e37

**Comment by ipasechnikov** [comment]
c50954da07075c41e94c1e2420b4711a5d1f1471 - trunc normal in `master-smurff-merge`
20fe4329bbb943b0aa882277937fd81d538723cf - trunc normal tests  in `master-smurff-merge`

All tests for trunc normal pass. So I suppose we may consider this issue fixed.
