### ISSUE TITLE
Segfault in utils/eval_rmse test case

### ISSUE THREAD

**Issue by ipasechnikov** [ExaScience/smurff#16]
Segfault error occurs during `utils/eval_rmse` test run.

How to reproduce:

1. Build smurff tests from `smurff` branch using appropriate Makefile
2. Run `tests` execution file

You should get an error message like this one below:
```
../../../smurff-cpp/tests.cpp:584: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
===========================================
test cases:  28 |  27 passed | 1 failed
assertions: 134 | 133 passed | 1 failed
```

**Comment by ipasechnikov** [comment]
There is a new temporary fix branch `issue-16` that was created from `smurff`. The issue should be fixed now, `utils/eval_rmse` test passes. But is it ok to fix this issue the way it is fixed? Cause too many things have changed, methods, their signatures, lots of new classes added so I might be missing and not taking into consideration something.

@tvandera, could you please review 021edff829d75c85ab3d365b7f6a48c81f1ddaaf commit? It's a tiny commit, so it won't take much time. There is now a noise pointer check, but we might want to add additional asserts to all methods that use this noise pointer. Also in `utils/eval_rmse` test itself `Model` object was not initialized and `Data` object didn't have any `center_mode` initialized too. At first I tried to set it to `none` but test failed because of wrong result, then I tried `global` and it did the job.

If everything is ok, then we'll just merge `issue-16` branch into `smurff` branch and then `smurff` branch into `master-smurff-merge` branch and continue working on issue #11.

**Comment by tvandera** [comment]
I accept this fix, but propose to keep the issue open to:
  1. add the assertions to noise
  2. maybe add a dummy _NoNoiseModel_

**Comment by tvandera** [comment]
Fixes in `tests.cpp` are OK

**Comment by ipasechnikov** [comment]
@tvandera, bf830efb273e99006dba84a0ad4752ec835ef839 adds noise assertions. Don't know about dummy `NoNoiseModel`. We'll discuss it later. So as you suggested, let's keep this issue open for now.
We'll merge `issue-16` branch as soon as we are finished with #11 issue, cause currently it is the main task for us.

**Comment by ipasechnikov** [comment]
Actually I have just merged `issue-16` branch into `smurff` branch (d7d7d85d8079bc5fb14f3bc7eb13d592e85de316) and then `smurff` into `master-smurff-merge` (390e794be1af6c59ddad3863fa7e28c4e103dbdd). All changes are now in `master-smurff-merge` branch. So `issue-16` branch is now removed.

**Comment by tvandera** [comment]
In 926a817e09add75564c8a50470fa843012000ed5 I've replaced noise with noise_ptr, added noise() function with assertion.

**Comment by tvandera** [comment]
Same for Session::data in 51b769714c730dc9918da2a9d0c51ade7440ae6e
