### ISSUE TITLE
Compare output of different versions

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#19]
Compare
* smurff 0.6.0
* smurff 0.7.0 
* macau

**Comment by tvandera** [comment]
The scripts in  10c6859d and c2aa741de could be used.

**Comment by tvandera** [comment]
Running `smurff` with only `--train` and `--test` should be equivalent to running the first Python macau example: in python/macau/examples/bpmf-mm.py

**Comment by ipasechnikov** [comment]
What exactly are the `train` and `test` files?

Can we use files from [examples](https://macau.readthedocs.io/en/latest/source/examples.html)?
```
wget http://homes.esat.kuleuven.be/~jsimm/chembl-IC50-346targets.mm
wget http://homes.esat.kuleuven.be/~jsimm/chembl-IC50-compound-feat.mm
```

I tried to pass them as `ic50_train` and `ic50_test` variables in [`test_macau.py`](https://github.com/ExaScience/smurff/blob/smurff/python/test/macau/test_macau.py) file but got an error:
```
ValueError: Y (15073 x 346) and Ytest (15073 x 105672) must have the same shape.
```

**Comment by jaak-s** [comment]
The first one (`chembl-IC50-346targets.mm`) is `Y` and second one (`chembl-IC50-compound-feat.mm`) is side information for rows, which you can add in python by adding `side = [X, None]`.

**Comment by ipasechnikov** [comment]
And what about `Ytest`? Where can I get it?

**Comment by jaak-s** [comment]
Here is an example how to make it (moves 20% of the Y to the test set):
```python
Ytrain, Ytest = macau.make_train_test(Y, 0.2)

## without side information
results = macau.macau(Y = Ytrain, Ytest = Ytest, num_latent = 4, burnin = 50, nsamples = 50)

## with side information
results = macau.macau(Y = Ytrain, Ytest = Ytest, side=[X, None], num_latent = 4, burnin = 50, nsamples = 50)
```

**Comment by ipasechnikov** [comment]
Firstly I tried running `macau` from [`test_macau.py`](https://github.com/ExaScience/smurff/blob/smurff/python/test/macau/test_macau.py).
```python
#!/usr/bin/env python

from macau import bpmf, macau, make_train_test
import scipy.io

datadir = "/home/ipasechnikov/"

ic50_train, ic50_test = make_train_test(scipy.io.mmread(datadir + "fold1_train.mtx"), 0.2)
result = bpmf(Y          = ic50_train,
              Ytest      = ic50_test,
              num_latent = 100,
              verbose    = True,
              burnin     = 20,
              nsamples   = 10)
```

Then I tried running `smurff`. Both matrix files used in `macau` and `smurff` are the same, one of them is just renamed.
```
./smurff --train chembl-IC50-346targets.mm --test 0.2 --num-latent 100 --burnin 20 --nsamples 10
```
Both these runs should do the same stuff, cause all command line arguments are the same, as far as I can see. Maybe some default command line arguments can mess things up a bit, but output is too different and `smurff` takes too much time, meaning that they might do completely different calculations.

#### macau output
```
Noise precision: 1.000000 (fixed)
Sampling
Iter   0: RMSE: 1.5735 (1samp: 1.5735)  U:[3.88e+02, 5.48e+01]	Side:[nan, nan] [took 1.6s]
Iter   1: RMSE: 1.4756 (1samp: 1.4756)  U:[3.88e+02, 5.42e+01]	Side:[nan, nan] [took 1.6s]
Iter   2: RMSE: 1.4067 (1samp: 1.4067)  U:[3.89e+02, 5.46e+01]	Side:[nan, nan] [took 1.6s]
Iter   3: RMSE: 1.3757 (1samp: 1.3757)  U:[3.89e+02, 5.52e+01]	Side:[nan, nan] [took 1.6s]
Iter   4: RMSE: 1.3352 (1samp: 1.3352)  U:[3.89e+02, 5.59e+01]	Side:[nan, nan] [took 1.6s]
Iter   5: RMSE: 1.3157 (1samp: 1.3157)  U:[3.90e+02, 5.64e+01]	Side:[nan, nan] [took 1.6s]
Iter   6: RMSE: 1.2804 (1samp: 1.2804)  U:[3.90e+02, 5.64e+01]	Side:[nan, nan] [took 1.6s]
Iter   7: RMSE: 1.2565 (1samp: 1.2565)  U:[3.90e+02, 5.64e+01]	Side:[nan, nan] [took 1.6s]
Iter   8: RMSE: 1.2476 (1samp: 1.2476)  U:[3.90e+02, 5.66e+01]	Side:[nan, nan] [took 1.6s]
Iter   9: RMSE: 1.2397 (1samp: 1.2397)  U:[3.90e+02, 5.58e+01]	Side:[nan, nan] [took 1.6s]
Iter  10: RMSE: 1.247 (1samp: 1.247)  U:[3.90e+02, 5.60e+01]	Side:[nan, nan] [took 1.6s]
Iter  11: RMSE: 1.2271 (1samp: 1.2271)  U:[3.90e+02, 5.51e+01]	Side:[nan, nan] [took 1.6s]
Iter  12: RMSE: 1.2233 (1samp: 1.2233)  U:[3.90e+02, 5.61e+01]	Side:[nan, nan] [took 1.6s]
Iter  13: RMSE: 1.2084 (1samp: 1.2084)  U:[3.90e+02, 5.53e+01]	Side:[nan, nan] [took 1.6s]
Iter  14: RMSE: 1.2002 (1samp: 1.2002)  U:[3.90e+02, 5.44e+01]	Side:[nan, nan] [took 1.6s]
Iter  15: RMSE: 1.2145 (1samp: 1.2145)  U:[3.90e+02, 5.43e+01]	Side:[nan, nan] [took 1.6s]
Iter  16: RMSE: 1.2033 (1samp: 1.2033)  U:[3.90e+02, 5.55e+01]	Side:[nan, nan] [took 1.6s]
Iter  17: RMSE: 1.2032 (1samp: 1.2032)  U:[3.89e+02, 5.45e+01]	Side:[nan, nan] [took 1.6s]
Iter  18: RMSE: 1.1921 (1samp: 1.1921)  U:[3.88e+02, 5.48e+01]	Side:[nan, nan] [took 1.6s]
Iter  19: RMSE: 1.1985 (1samp: 1.1985)  U:[3.88e+02, 5.52e+01]	Side:[nan, nan] [took 1.6s]
 ====== Burn-in complete, averaging samples ====== 
Iter  20: RMSE: 1.1986 (1samp: 1.1986)  U:[3.88e+02, 5.50e+01]	Side:[nan, nan] [took 1.6s]
Iter  21: RMSE: 1.0886 (1samp: 1.1869)  U:[3.87e+02, 5.46e+01]	Side:[nan, nan] [took 1.6s]
Iter  22: RMSE: 1.0522 (1samp: 1.1956)  U:[3.87e+02, 5.41e+01]	Side:[nan, nan] [took 1.6s]
Iter  23: RMSE: 1.0332 (1samp: 1.193)  U:[3.88e+02, 5.40e+01]	Side:[nan, nan] [took 1.6s]
Iter  24: RMSE: 1.0223 (1samp: 1.195)  U:[3.88e+02, 5.37e+01]	Side:[nan, nan] [took 1.6s]
Iter  25: RMSE: 1.0174 (1samp: 1.2048)  U:[3.88e+02, 5.45e+01]	Side:[nan, nan] [took 1.6s]
Iter  26: RMSE: 1.0118 (1samp: 1.191)  U:[3.87e+02, 5.45e+01]	Side:[nan, nan] [took 1.6s]
Iter  27: RMSE: 1.0074 (1samp: 1.1953)  U:[3.87e+02, 5.57e+01]	Side:[nan, nan] [took 1.6s]
Iter  28: RMSE: 1.0038 (1samp: 1.1904)  U:[3.86e+02, 5.48e+01]	Side:[nan, nan] [took 1.6s]
Iter  29: RMSE: 1.0014 (1samp: 1.1924)  U:[3.86e+02, 5.59e+01]	Side:[nan, nan] [took 1.6s]

```

#### smurff output
```
MacauSession {
  Data: {
    Type: ScarceMatrixData [with NAs]
    Component-wise mean: 6.35397
    Center: global
    Noise: Fixed gaussian noise with precision: 5
    Size: 47424 [15073 x 346] (0.909332%)
      Warning: 2 empty cols
      Warning: 104 empty rows
  }
  Model: {
    Num-latents: 100
  }
  Priors: {
    0: NormalPrior
    1: NormalPrior
  }
  Result: {
    Test data: 11856 [0 x 0] (inf%)
    RMSE using globalmean: nan
    RMSE using colmean: nan
    RMSE using rowmean: nan
  }
  Version: v0.6.0-162-g827c6ad
  Iterations: 20 burnin + 10 samples
  Save model: never
}
Initial   0/  0: RMSE: nan (1samp: nan)  U:[0.00e+00, 0.00e+00] [took: 0.0s]
 ====== Sampling (burning phase) ====== 
Burnin   1/ 20: RMSE: nan (1samp: nan)  U:[5.92e+01, 3.91e+02] [took: 77.2s]
Burnin   2/ 20: RMSE: nan (1samp: nan)  U:[1.95e+01, 1.05e+01] [took: 76.7s]
Burnin   3/ 20: RMSE: nan (1samp: nan)  U:[1.00e+01, 1.00e+01] [took: 78.0s]
Burnin   4/ 20: RMSE: nan (1samp: nan)  U:[1.01e+01, 9.99e+00] [took: 77.3s]
Burnin   5/ 20: RMSE: nan (1samp: nan)  U:[1.00e+01, 9.99e+00] [took: 80.2s]
Burnin   6/ 20: RMSE: nan (1samp: nan)  U:[1.01e+01, 1.00e+01] [took: 79.5s]
Burnin   7/ 20: RMSE: nan (1samp: nan)  U:[1.01e+01, 1.00e+01] [took: 80.5s]
Burnin   8/ 20: RMSE: nan (1samp: nan)  U:[1.00e+01, 1.00e+01] [took: 80.5s]
Burnin   9/ 20: RMSE: nan (1samp: nan)  U:[1.01e+01, 9.99e+00] [took: 78.5s]
Burnin  10/ 20: RMSE: nan (1samp: nan)  U:[1.02e+01, 1.00e+01] [took: 79.5s]
Burnin  11/ 20: RMSE: nan (1samp: nan)  U:[1.01e+01, 1.00e+01] [took: 78.6s]
Burnin  12/ 20: RMSE: nan (1samp: nan)  U:[1.00e+01, 9.99e+00] [took: 78.2s]
Burnin  13/ 20: RMSE: nan (1samp: nan)  U:[1.01e+01, 1.00e+01] [took: 77.7s]
Burnin  14/ 20: RMSE: nan (1samp: nan)  U:[9.98e+00, 1.00e+01] [took: 78.4s]
Burnin  15/ 20: RMSE: nan (1samp: nan)  U:[9.99e+00, 1.00e+01] [took: 80.1s]
Burnin  16/ 20: RMSE: nan (1samp: nan)  U:[1.01e+01, 9.99e+00] [took: 78.0s]
Burnin  17/ 20: RMSE: nan (1samp: nan)  U:[1.01e+01, 1.00e+01] [took: 78.6s]
Burnin  18/ 20: RMSE: nan (1samp: nan)  U:[1.01e+01, 1.00e+01] [took: 79.2s]
Burnin  19/ 20: RMSE: nan (1samp: nan)  U:[1.02e+01, 9.99e+00] [took: 78.8s]
Burnin  20/ 20: RMSE: nan (1samp: nan)  U:[9.99e+00, 9.99e+00] [took: 79.6s]
 ====== Burn-in complete, averaging samples ====== 
Sample   1/ 10: RMSE: nan (1samp: nan)  U:[1.00e+01, 1.00e+01] [took: 79.6s]
```

As you can see `RMSE` and `1samp` are `nan` in smurff, whereas `macau` has at least them set.

And about this line in `macau` output. Should I pass precision in `smurff` too as `--precision 1.0` parameter?
```
Noise precision: 1.000000 (fixed)
```

**Comment by ipasechnikov** [comment]
It seems that you have partially fixed issue with `nan` and `inf`.

#### Before fix (827c6ad9388b1919d65217b463f64a9ddb6013ef)
<pre>
<code>
  Result: {
    Test data: 11856 <b>[0 x 0]</b> (<b>inf</b>%)
    RMSE using globalmean: <b>nan</b>
    RMSE using colmean: <b>nan</b>
    RMSE using rowmean: <b>nan</b>
  }
</code>
</pre>

<pre>
<code>
Initial   0/  0: RMSE: <b>nan</b> (1samp: <b>nan</b>)  U:[0.00e+00, 0.00e+00] [took: 0.0s]
 ====== Sampling (burning phase) ====== 
Burnin   1/ 20: RMSE: <b>nan</b> (1samp: <b>nan</b>)  U:[5.92e+01, 3.91e+02] [took: 77.2s]
</code>
</pre>


#### After fix (fc1fb0a039f1a3db1f4302fb85d451013e98d6ad latest commit for now)
<pre>
<code>
  Result: {
    Test data: 11856 <b>[15073 x 346]</b> (<b>0.227333</b>%)
    RMSE using globalmean: <b>1.36621</b>
    RMSE using colmean: <b>1.16769</b>
    RMSE using rowmean: <b>1.23947</b>
  }
</code>
</pre>

<pre>
<code>
Initial   0/  0: RMSE: <b>nan</b> (1samp: <b>1.3662</b>)  U:[0.00e+00, 0.00e+00] [took: 0.0s]
====== Sampling (burning phase) ====== 
Burnin   1/ 20: RMSE: <b>nan</b> (1samp: <b>1.6906</b>)  U:[5.85e+01, 3.88e+02] [took: 78.4s]
</code>
</pre>

Results still differ from `macau`, but I suppose that's my bad. I might have passed some wrong arguments. I'll double check it and try to figure out why `RMSE` is still `nan`.

**Comment by ipasechnikov** [comment]
## NAN problem

<pre>
<code>
Initial   0/  0: RMSE: <b>nan</b> (1samp: 1.3662)  U:[0.00e+00, 0.00e+00] [took: 0.0s]
</code>
</pre>

The problem with the `RMSE` `nan` is that `rmse_avg` is not calculated during `burnin` phase.

As you can see in [`result.cpp:101`](https://github.com/ExaScience/smurff/blob/master-smurff-merge/lib/smurff-cpp/result.cpp#L101) , `rmse_avg` is not calculated, only `rmse`.
So we can fix this output somehow in [`session.cpp:488`](https://github.com/ExaScience/smurff/blob/master-smurff-merge/lib/smurff-cpp/session.cpp#L488), for example just checking if this is `burnin` phase.

## Calculation results

What's more, I tried to remove randomness from `macau` just for testing. 

[macau.cpp:73](https://github.com/jaak-s/macau/blob/master/lib/macau-cpp/macau.cpp#L73)
```C++
  //unsigned seed1 = std::chrono::system_clock::now().time_since_epoch().count();
  unsigned seed1 = 1234;
```

[mvnormal.cpp:38](https://github.com/jaak-s/macau/blob/master/lib/macau-cpp/mvnormal.cpp#L38)
```C++
//static std::mt19937 rng(srd());
static std::mt19937 rng(1234);
```
In [macau.pyx](https://github.com/jaak-s/macau/blob/master/python/macau/macau.pyx) [`make_train_test`](https://github.com/jaak-s/macau/blob/master/python/macau/macau.pyx#L125) and [`make_train_test_df`](https://github.com/jaak-s/macau/blob/master/python/macau/macau.pyx#L149) are also altered.

```python
    np.random.seed(1234);
    rperm = np.random.permutation(Y.nnz)
```
Python code that was used to test `macau`.
```python
from macau import bpmf, macau, make_train_test
import scipy.io

datadir = "/home/ipasechnikov/"

ic50_train, ic50_test = make_train_test(scipy.io.mmread(datadir + "chembl-IC50-346targets.mm"), 0.2)
scipy.io.mmwrite(datadir + "chembl-IC50-test", ic50_test)

result = bpmf(Y          = ic50_train,
              Ytest      = ic50_test,
              num_latent = 10,
              verbose    = True,
              burnin     = 20,
              nsamples   = 10)
```
Also as you can see in python script, test matrix is saved as a file now, so that I can use it to test `smurff` in case `smurff` creates test matrix somehow differently.

Pretty much the same changes were done to `smurff`. `init_bmrng` now uses constant seed too. Also, as far as I can see, we can't choose noise now, even if I pass `precision` argument, I still end up with no noise model. So I hard-coded noise in `smurff` so that `FixedCaussianNoise is used.

These are changes just to make testing a bit more easier for me, they are local and by no means will be committed.

And still I get different results for `macau` and `smurff`. Even though they are the same for each one between the runs, but between `macau` and `smurff` they are different.

What's more, I'm not quite sure what I'm looking for, what exactly should be the same in output? Just everything? Both `RMSE` and `U`? At least their initial values?

**Comment by tvandera** [comment]
The NAN is OK, since the average RMSE is not calculated in the burnin phase. Macau prints the 1sample RMSE in the burning phase; SMURFF prints NAN.
