### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by jaak-s** [ExaScience/smurff#20]
It would be nice to turn on Travic continuous integration for Smurff. It allows automatic running of the test suit on every commit, get immediate e-mail if something breaks the master branch. And it is free for open source projects in github.

I would propose to set it up for compiling the C++ library and then executing the tests in `tests.cpp`. Possible later we can also add Python tests (like `test_macau.py` etc).

**Comment by motoharu-yano** [comment]
I started investigating this. I have added some initial travis yml file to the repo. However I am not able to do anything further since it looks like I do not have sufficient rights.

**Comment by motoharu-yano** [comment]
I have configured Travis build. 
https://travis-ci.org/ExaScience/smurff
Build matrix now consists of Debug and Release build.
After each build tests are executed.
Build status is also attached to readme page.
