### ISSUE TITLE
 #27 var_total does not subtract mean

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#27]
correct in master branch:
>      se += square(it.value() - mean_value);

incorrect in master-smurff-merge branch
>    se += square(it.value());

needs to be fixed for sparse and dense data.

**Comment by tvandera** [comment]
It might be correct after all, since the centered version of Y is used:
>    auto &Y = Yc.at(0);

**Comment by tvandera** [comment]
But only of centering mode is global

**Comment by motoharu-yano** [comment]
Old and new version of var_total is placed to data.cpp for comparison.

**Comment by tvandera** [comment]
Possible fix in 20b7e0a, but the code currently does not compiled -> difficult to test...
