### ISSUE TITLE
NoiseConfig not copied

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#28]
master-smurff-merge branch, gen_random.cpp, `extract`:

>    MatrixConfig Ynew(Yin.nrow, Yin.ncol, Ynew_nnz);

add noise config in c'tor

**Comment by ipasechnikov** [comment]
@tvandera, it seems that this issue can be closed, but there is still one question left.

Does output `MatrixConfig` from `gen_random` function should have the same `NoiseConfig` as input `MatrixConfig`? For now I added that it should have the same `NoiseConfig`. Maybe that is wrong and it should have no `NoiseConfig`.
https://github.com/ExaScience/smurff/blob/3d088add832427fcb6e013178d021a4955748d82/lib/smurff-cpp/gen_random.cpp#L198-L206

**Comment by tvandera** [comment]
Ok like this
