### ISSUE TITLE
Bugs in extract

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#30]
1. Fix bug in `MatrixConfig extract(MatrixConfig &Yin, double s, bool remove, std::default_random_engine::result_type seed)`

Current code:
```
	      if (udist(gen) < s && Yout_rows.size() < Yout_nnz)
```
Probable fix:
```
	      if (udist(gen) < s && Yout_rows.size() < Yout_nnz ||
	          Ynew_values.size() >= Ynew_nnz)
```
2. Comment on indeterministic behavior
3. Remove from cmd line args

**Comment by ipasechnikov** [comment]
@tvandera, have updated everything that was listed above.

This function won't fail here anymore:
https://github.com/ExaScience/smurff/blob/60be3be80815c8e48a6cc8e511c225452f087fd3/lib/smurff-cpp/gen_random.cpp#L208-L214

But instead it will fail here:
https://github.com/ExaScience/smurff/blob/60be3be80815c8e48a6cc8e511c225452f087fd3/lib/smurff-cpp/gen_random.cpp#L217

We can leave it as it is now, I suppose.

**Comment by tvandera** [comment]
Let's leave it at this - since the function is no longer supported.

**Comment by tvandera** [comment]
extract removed from code base
