### ISSUE TITLE
Move code sample_latents to update_prior

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#32]
Orginal commend in #11:

Pseudocode explanation about possible update_prior issue:

new code

void MacauPrior::sample_latents()
NormalPrior::sample_latents();
ILatentPrior::sample_latents();
for(int n = 0; n < U().cols(); n++)
sample_latent(n);
void NormalPrior::sample_latent(int n)
NormalPrior::update_prior
MacauPrior::update_prior

old code

void MacauPrior::sample_latents
for(int n = 0; n < N; n++) {
sample_latent_blas

void MacauPrior::update_prior()

**Comment by tvandera** [comment]
Bug confirmed in discussion.
Discussed solution:
- move code from sample_latents to update_prior
- call update_prior at end of void ILatentPrior::sample_latents()

**Comment by motoharu-yano** [comment]
I have added separate branch where update_prior method is added.
It is called add-update-prior

**Comment by tvandera** [comment]
Verified on test suite. Branch merged. Ticket closed. Weekend!
