### ISSUE TITLE
Use 64bit types for read_sdm, read_ddm, ...

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#34]
Use 'int64_t' types for reading and writing binary matrix files.
Use python code as golden standard:

https://github.com/ExaScience/smurff/blob/master-smurff-merge/python/io/matrix_io.py

**Comment by ipasechnikov** [comment]
All functions from [`matrix_io.py`](https://github.com/ExaScience/smurff/blob/master-smurff-merge/python/io/matrix_io.py) are now in [`matrix_io.h`](https://github.com/ExaScience/smurff/blob/2617ef30e081fee8e22bab3d3b9708ead3cb0517/lib/smurff-cpp/matrix_io.h). New tests were added to [`tests.cpp`](https://github.com/ExaScience/smurff/blob/master-smurff-merge/lib/smurff-cpp/tests.cpp) to test these new functions. Old `matrix_io` functions were also fixed.
https://github.com/ExaScience/smurff/blob/2617ef30e081fee8e22bab3d3b9708ead3cb0517/lib/smurff-cpp/matrix_io.h#L216-L232

[`TensorConfig`](https://github.com/ExaScience/smurff/blob/master-smurff-merge/lib/smurff-cpp/TensorConfig.h) and [`MatrixConfig`](https://github.com/ExaScience/smurff/blob/master-smurff-merge/lib/smurff-cpp/MatrixConfig.h) classes were also updated. Now they use fixed size types.

**Comment by tvandera** [comment]
Seems like bug here:

https://github.com/ExaScience/smurff/blob/2617ef30e081fee8e22bab3d3b9708ead3cb0517/lib/smurff-cpp/matrix_io.cpp#L657

**Comment by motoharu-yano** [comment]
I think this is now done. We have all i/o implemented for matrices and tensors using correct types.
