### ISSUE TITLE
Build of smurff for Windows

### ISSUE THREAD

**Issue by motoharu-yano** [ExaScience/smurff#35]
It would be nice to have a build for Windows. I have already added cmake support.
However there are some problems with dependencies for Windows.
Main problem is argp library. Need to figure what can be used on Windows.

**Comment by tvandera** [comment]
Maybe we can include this as a git submodule: https://github.com/alexreg/libargp

**Comment by motoharu-yano** [comment]
Some time ago I have briefly checked this issue again. Openblas including lapack can be compiled on Windows using mingw-64. However it does not work for mingw-32. 
There are still problems with libargp though.
Binary distribution from gnu win32 is only 32 bit. libargp from repo does not compile.
And if updated with gnulib-tool it still has compilation issues.

**Comment by tvandera** [comment]
Can you see if libsmurff-cpp compiles? We can do the command line interface using python, like in black_smurff.

**Comment by motoharu-yano** [comment]
We now have separate branch called win-build.
Build now works on windows. Cmd line parser is implemented with boost options.
We decided to remove argp dependency and use boost parser instead.
https://github.com/ExaScience/smurff/issues/67
The last thing to do at the moment is to add readme for windows build.

**Comment by motoharu-yano** [comment]
Readme was added in previous commits.
