### ISSUE TITLE
Under I/O loading: consolidate a single matrix_io.py library

### ISSUE THREAD

**Issue by golipe** [ExaScience/smurff#39]
There are several versions of the same functions. 
Felipe will merge them to obtain a reference matrix_io.py for furhter commits.

**Comment by tvandera** [comment]
Golden reference in:
https://github.com/ExaScience/smurff/tree/master/python/matrix_io

Can be install as a python package.
Also available on anaconda.org:
https://anaconda.org/vanderaa/matrix_io
