### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#4]
- Existing tests in "jaak-s/macau"
   - https://github.com/jaak-s/macau/blob/master/lib/macau-cpp/tests.cpp 
- All tests should be transferred to "ExaScience/smurff"
   - https://github.com/ExaScience/smurff/blob/smurff/lib/smurff-cpp/tests.cpp
- Objective: 
   - reduce number of failing tasks
   - transfer missing unit tests from "jaak-s/macau" to  "ExaScience/smurff"

**Comment by tvandera** [comment]
Start by running tests from tests.cpp
Suggestions for more tests are welcome

**Comment by ipasechnikov** [comment]
These tests are currently in `master-smurff-merge` branch. They all pass.
1. `SparseFeat/At_mul_A_bcsr`
2. `SparseFeat/At_mul_A_csr`
3. `linop/A_mul_Bx(csr)`
4. `linop/AtA_mul_Bx(csr)`
5. `SparseFeat/compute_uhat`
6. `SparseFeat/solve_blockcg`
7. `SparseFeat/solve_blockcg_1_0`
8. `MatrixXd/compute_uhat`
9. `linop/solve_blockcg_dense`
10. `chol/chol_solve_t`
11. `mvnormal/rgamma`
12. `latentprior/sample_lambda_beta`
13. `linop/A_mul_At_omp`
14. `linop/A_mul_At_combo`
15. `linop/A_mul_B_omp`
16. `linop/A_mul_B_omp/speed`
17. `linop/A_mul_B_add`
18. `linop/At_mul_Bt/SparseFeat`
19. `linop/At_mul_Bt/SparseDoubleFeat`
20. `linop/add_Acol_mul_bt/SparseFeat`
21. `linop/add_Acol_mul_bt/SparseDoubleFeat`
22. `linop/At_mul_A_blas`
23. `linop/A_mul_At_blas`
24. `linop/A_mul_B_blas`
25. `linop/At_mul_B_blas`
26. `linop/A_mul_Bt_blas`
27. `utils/split_work_mpi`
28. `utils/sparseFromIJV`
29. `utils/eval_rmse`
30. `utils/row_mean_var`
31. `inv_norm_cdf/inv_norm_cdf`
32. `truncnorm/norm_cdf`
33. `truncnorm/rand_truncnorm`

Also there is a newer version of `utils/sparseFromIJV` test in macau. It tests `sparseFromIJV` that uses `idx`.  We don't have this method now, we have `sparse_to_eigen` instead I suppose. So currently this version of a test is commented.

These are the tests that are related to tensors. So they all are commented out.
1. `sparsetensor/sparsemode`
2. `bpmfutils/eval_rmse_tensor`
3. `sparsetensor/sparsetensor`
4. `sparsetensor/vectorview`
5. `latentprior/sample_tensor`
6. `macauoneprior/sample_tensor_uni`

And the last missing test is `macauprior/make_dense_prior`, cause we don't have any `make_dense_prior` function. Maybe we have the same functionality in smurff, don't know.

**Comment by tvandera** [comment]
The `make_dense_prior` should be ported to smurff, since the the macauprior in smurff supports dense information. Might not be trivial though.

Otherwise looks fine for now.

We'll have to add more tests since a lot of the functionality in smurff is not yet tested

**Comment by tvandera** [comment]
make_dense_prior: obsolete, we now use PriorFactory
