### ISSUE TITLE
Cholesky decomposition, LAPACK dependency

### ISSUE THREAD

**Issue by motoharu-yano** [ExaScience/smurff#41]
Currently we depend on LAPACK library for calculating Cholesky decomposition.
The other example in the code is usage of Cholesky decomposition from Eigen library.
For example in NormalPrior.cpp (line 112).
We were considering removing LAPACK dependency. 
However here is comment from Jaak:

> Original code supports Cholesky with standard BLAS too (but requires linking to LAPACK). However, the dependency to OpenBLAS is due speed difference. OpenBLAS has multi-core support and in high-end hardware can be around 20x-50x faster.
The eigen implementation of Cholesky unfortunately is also 1-threaded and very slow. Having fast Cholesky is important for supporting dense side information for Macau.

**Comment by tvandera** [comment]
This probably means we cannot break the dependency with LAPACK. We better make it explicit then. 

A cleaner solution, still using LAPACK, that would also boost the speed of other parts in SMURFF is to use `-DEIGEN_USE_BLAS` and `-DEIGEN_USE_LAPACKE`.

**Comment by tvandera** [comment]
cholesky at these lines:

https://github.com/ExaScience/smurff/blob/204e1fc6be69953e2b22dca764c2fcaf4879d800/lib/smurff-cpp/SmurffCpp/Priors/MacauPrior.hpp#L210

needs to be optimized

**Comment by tvandera** [comment]
We keep LAPACK dependency.
