### ISSUE TITLE
Implement dense matrix text file format

### ISSUE THREAD

**Issue by ipasechnikov** [ExaScience/smurff#43]
Currently there is only binary file format available for dense matrices.

Use the following resources:
- http://math.nist.gov/MatrixMarket/formats.html
- [MMformat.pdf](https://github.com/ExaScience/smurff/files/1398286/MMformat.pdf)

**Comment by tvandera** [comment]
For writing there are CSV files

**Comment by ipasechnikov** [comment]
Available since 88fa68d96fbe14dab4139e1cb7d4a64bc7a0a4f6 commit.
