### ISSUE TITLE
Macro definition options

### ISSUE THREAD

**Issue by motoharu-yano** [ExaScience/smurff#45]
We still have these ifdefs:
#ifdef PROFILING
#ifdef TEST_MVNORMAL
#ifdef OPENBLAS
#ifdef NDEBUG

In case we need any - better way would be to have some options in root cmake file to enable these defines. This will clearly state which defines we have.
If we dont need these - probably it is better to remove them.

**Comment by tvandera** [comment]
- PROFILING: make an option of CMake
- TEST_MVNORMAL: remove code inside ifdefs + ifdef
- OPENBLAS: keep as is
- NDEBUG: keep as is

**Comment by tvandera** [comment]
done
