### ISSUE TITLE
Possible row/column mismatch

### ISSUE THREAD

**Issue by motoharu-yano** [ExaScience/smurff#46]
https://github.com/ExaScience/smurff/blob/master/lib/smurff-cpp/SmurffCpp/Model.cpp#L87
It looks like row and col dimensions are switched?

**Comment by tvandera** [comment]
Why do you think so?

**Comment by tvandera** [comment]
?

**Comment by motoharu-yano** [comment]
Closing this issue. We talked this through and it was explained that the purpose of V method is to return the "other" sample matrix. Or in case of Tensors this can be described as VectorView that selects all "other" sample matrices except the matrix that corresponds to current dimension (a U matrix).
