### ISSUE TITLE
Remove centring code

### ISSUE THREAD

**Issue by motoharu-yano** [ExaScience/smurff#48]
Centring code is already removed from the library in remove-data-centring-new branch.
Tom has also prepared python script that generates centered data.
We also already have testing framework to run tests with different combinations of arguments.
The only thing left is to run the tests and compare the results.
We need to verify the following cases:
- Run latest smurff without centring options (no centring). Run centring branch smurff. Use both uncentered data and centered data. Compare results for no centring scenario in latest smurff.
- Run latest smurff with centring options. Run centring branch smurff. Use uncentered data for latest smurff. Use centered data for centring branch smurff. Compare results.

**Comment by ipasechnikov** [comment]
Here is a table of input data type and command line arguments that should be used for each branch.
Fox example first row means that you use **non-centered** data and `--center none` command line argument when running `master` branch and **non-centered** data with no `--center` command line argument when running `remove-data-centring-new` branch.
<table>
<tr>
<th colspan="2"><code>master</code></th>
<th colspan="2"><code>remove-data-centring-new</code></th>
</tr>
<tr>
<td align="center">Data</td>
<td align="center">Command line arguments</td>
<td align="center">Data</td>
<td align="center">Command line arguments</td>
</tr>
<tr>
<td align="center">non-centered</td>
<td align="center"><code>--center none</code></td>
<td align="center">non-centered</td>
<td align="center">NA</td>
</tr>
<tr>
<td align="center">col-centered</td>
<td align="center"><code>--center none</code></td>
<td align="center">col-centered</td>
<td align="center">NA</td>
</tr>
<tr>
<td align="center">row-centered</td>
<td align="center"><code>--center none</code></td>
<td align="center">row-centered</td>
<td align="center">NA</td>
</tr>
<tr>
<td align="center">non-centered</td>
<td align="center"><code>--center cols</code></td>
<td align="center">col-centered</td>
<td align="center">NA</td>
</tr>
<tr>
<td align="center">non-centered</td>
<td align="center"><code>--center rows</code></td>
<td align="center">row-centered</td>
<td align="center">NA</td>
</tr>
</table>

**Comment by ipasechnikov** [comment]
All tests were run with the latest `master` and `remove-data-centring-new` at that moment. 9827b14a0226b700cbb6d882e9df5a429f3df85f and 4e703a8297af778474bbeb716466b51b3fbc2ccf respectively.

To get conda recipe for `remove-data-centring-new` branch and updated version of `collect_results.py` you should use at least a5a03408bc1878340182b58aeea03f8d134b1d17 commit.

All commands are given in the order of table rows above.
```
# 1st row

# master branch with non-centered data and '--centered none' command line argument
find ./work/latest/smurff-latest/synthetic/*_none -name cmd | grep none/direct | xargs -n1 -t bash -e

# remove-data-centring-new branch with non-centered data
find ./work/latest/smurff-centering/synthetic/*_none -name cmd | grep none/direct | xargs -n1 -t bash -e
```

```
# 2nd row

# master branch with col-centered data and '--centered none' command line argument
find ./work/latest/smurff-latest/synthetic/*_col -name cmd | grep none/direct | xargs -n1 -t bash -e

# remove-data-centring-new branch with col-centered data
find ./work/latest/smurff-centering/synthetic/*_col -name cmd | grep none | xargs -n1 -t bash -e
```

```
# 3rd row

# master branch with row-centered data and '--centered none' command line argument
find ./work/latest/smurff-latest/synthetic/*_row -name cmd | grep none/direct | xargs -n1 -t bash -e

# remove-data-centring-new branch with row-centered data
find ./work/latest/smurff-centering/synthetic/*_row -name cmd | grep none | xargs -n1 -t bash -e
```

```
# 4th row

# master branch with global-centered data and '--centered none' command line argument
find ./work/latest/smurff-latest/synthetic/*_global -name cmd | grep none/direct | xargs -n1 -t bash -e

# remove-data-centring-new branch with global-centered data
find ./work/latest/smurff-centering/synthetic/*_global -name cmd | grep none | xargs -n1 -t bash -e
```

```
# 5th row

# master branch with non-centered data and '--centered cols' command line argument
find ./work/latest/smurff-latest/synthetic/*_none -name cmd | grep cols | xargs -n1 -t bash -e

# remove-data-centring-new branch with col-centered data
find ./work/latest/smurff-centering/synthetic/*_col -name cmd | grep none | xargs -n1 -t bash -e
```

```
# 6th row

# master branch with non-centered data and '--centered rows' command line argument
find ./work/latest/smurff-latest/synthetic/*_none -name cmd | grep rows | xargs -n1 -t bash -e

# remove-data-centring-new branch with row-centered data
find ./work/latest/smurff-centering/synthetic/*_row -name cmd | grep none | xargs -n1 -t bash -e
```

```
# 7th row

# master branch with non-centered data and '--centered global' command line argument
find ./work/latest/smurff-latest/synthetic/*_none -name cmd | grep global | xargs -n1 -t bash -e

# remove-data-centring-new branch with global-centered data
find ./work/latest/smurff-centering/synthetic/*_global -name cmd | grep none | xargs -n1 -t bash -e
```

After running all commands, you run `collect_result.py` in `./work/latest` directory to get a bunch of `results.csv` files.
