### ISSUE TITLE
Integration Testing

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#5]
- Existing tests in "jaak-s/macau"
    - https://github.com/jaak-s/macau/blob/master/python/macau/test_macau.py
 - All tests should be transferred to "ExaScience/smurff"
    - https://github.com/ExaScience/smurff/blob/smurff/python/smurff/test/test_bpmf.py
    - Rename test_bpmf.py into test_smurff.py in "ExaScience/smurff"
 - Dependency on Task 9 (python interface for SMURFF)
 - TODO
    - @Felipe - get unit case on six targets, please provide data and hackaton method. Which method was used? (regression testing)
    - @Felipe - add integration test to python code

**Comment by tvandera** [comment]
+ some other .py scripts in python/macau

**Comment by ipasechnikov** [comment]
Can I remove this this test? Seems like we don't need it anymore cause it uses C++ matrix split that we removed long time ago.
https://github.com/ExaScience/smurff/blob/204e1fc6be69953e2b22dca764c2fcaf4879d800/python/smurff/test/test_bpmf.py#L7-L9

**Comment by tvandera** [comment]
Euh, I think this is the equivalent of:
`./smurff --train X --num-latent=10 --burnin=10 --nsamples=15`
which should work

**Comment by tvandera** [comment]
The line 
`X = scipy.sparse.rand(15, 10, 0.2) `
generates of sparse random matrix with 15 rows, 10 columns and a density of 20%.

**Comment by ipasechnikov** [comment]
Current status update
1. All [`test_bpmf.py`](https://github.com/ExaScience/smurff/blob/master/python/smurff/test/test_bpmf.py) tests now pass
2. Moved [`test_macau.py`](https://github.com/ExaScience/smurff/blob/d617365bbea4d71655ec93a768430fd56382bb58/python/macau/test_macau.py) to [`test_smurff.py`](https://github.com/ExaScience/smurff/blob/master/python/smurff/test/test_smurff.py). Python wrapper does not support tensors for now, so they are commented out. Have to figure out how to adapt them.

And I have a few questions.

-------

##### 1. Can we consider these lines being the same?

https://github.com/ExaScience/smurff/blob/d617365bbea4d71655ec93a768430fd56382bb58/python/macau/test_macau.py#L23-L32

https://github.com/ExaScience/smurff/blob/748abe5feaaa656c37278d6cbcd61c98d0489386/python/smurff/test/test_smurff.py#L21-L28

Had to flip arguments when calling `np.random.rand` for columns side info. Cause columns side info should have the same amount of columns as train data.
```python
# Before
side2 = scipy.sparse.coo_matrix( np.random.rand(20, 3) ) 

# After
side2 = scipy.sparse.coo_matrix( np.random.rand(3, 20) ) 
```

---

##### 2. `test_too_many_sides` and `test_macau_tensor`
Seems like old macau could provide side info for each dimension. But now we can only provide for cols and rows. How should we handle this?

---

##### 3. `test_bpmf_emptytest`

https://github.com/ExaScience/smurff/blob/d617365bbea4d71655ec93a768430fd56382bb58/python/macau/test_macau.py#L80-L82

This test doesn't make much sense now. We don't require to pass test matrix, but in this case test matrix presents. The thing is it doesn't have any values so the check in `Config::validate` method fails. Should we remove this test?

https://github.com/ExaScience/smurff/blob/748abe5feaaa656c37278d6cbcd61c98d0489386/lib/smurff-cpp/SmurffCpp/Configs/Config.cpp#L90-L93

---

@tvandera, it would be nice, if you could skim through [`test_smurff.py`](https://github.com/ExaScience/smurff/blob/748abe5feaaa656c37278d6cbcd61c98d0489386/python/smurff/test/test_smurff.py) and review tests that already there.

**Comment by tvandera** [comment]
Hi Ilya,

1. Yes those test seem equal.
2. If we support tensors we should have a way to provide side info for each dimension
3. Replace with not passing any `Ytest`??

**Comment by ipasechnikov** [comment]
@tvandera,
2. Not quite actually. Currently we can only pass `row_features` and `col_features` even in C++. So that is only 2 dimensions
3. Indeed, right

**Comment by ipasechnikov** [comment]
Current status:
1. All Python tests are located in https://github.com/ExaScience/smurff/tree/master/python/smurff/test
2. [test_bpmf.py](https://github.com/ExaScience/smurff/blob/master/python/smurff/test/test_bpmf.py) contains old smurff tests
3. [test_smurff.py](https://github.com/ExaScience/smurff/blob/master/python/smurff/test/test_smurff.py) contains [macau](https://github.com/jaak-s/macau/blob/master/python/macau/test_macau.py) tests
4. Probit tests in [test_smurff.py](https://github.com/ExaScience/smurff/blob/master/python/smurff/test/test_smurff.py) are disabled for now. Currently probit noise is not available in Python interface

**Comment by ipasechnikov** [comment]
Updated Python interface to support probit noise. So [test_smurff.py](https://github.com/ExaScience/smurff/blob/master/python/smurff/test/test_smurff.py) now has probit tests enabled except for the [`test_macau_dense_probit`](https://github.com/ExaScience/smurff/blob/master/python/smurff/test/test_smurff.py#L90) cause it passes features to `macau` prior and currently we do not support features for tensor data. So this test is just skipped for now.

In total there are 3 skipped tests:
- [`test_macau_dense_probit`](https://github.com/ExaScience/smurff/blob/master/python/smurff/test/test_smurff.py#L90)
- [`test_macau_tensor`](https://github.com/ExaScience/smurff/blob/master/python/smurff/test/test_smurff.py#L415)
- [`test_macau_tensor_univariate`](https://github.com/ExaScience/smurff/blob/master/python/smurff/test/test_smurff.py#L435)

When tensor data supports features and aux-data then we can simply remove `@unittest.skip` decorators for these tests.

**Comment by tvandera** [comment]
Cool. Seems to work form after some minor fixes.

**Comment by tvandera** [comment]
Further python work happening in #84
