### ISSUE TITLE
Generate Predictions (ignoring the test set)

### ISSUE THREAD

**Issue by golipe** [ExaScience/smurff#50]
The function should ask for input:
range of consecutive rows
range of consecutive columns
path to the stored models

It should return:
The average and standard deviation of the multiplication of U*V'  for all available samples (previously stored) for the requested matrix block

Typical use case:
retreive 1K rows every time until all rows are covered. Store the predictions by chunks of 1K rows.

**Comment by motoharu-yano** [comment]
This issue is related to https://github.com/ExaScience/smurff/issues/51

**Comment by tvandera** [comment]
- `predict.py` script - tested by @golipe 
- todo: add similar script for feature-matrices from `MacauPrior`

**Comment by tvandera** [comment]
Done.
