### ISSUE TITLE
test matrix is required

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#62]
if I don't pass `--test` I get the assertion:
```
Assertion failed: (!Y.isDense()), function set, file /Users/vanderaa/excape/smurff/lib/smurff-cpp/SmurffCpp/result.cpp, line 27.
```

**Comment by motoharu-yano** [comment]
As discussed - there should be a possibility to run smurff without specifying --train data.
This issue is related to https://github.com/ExaScience/smurff/issues/51

**Comment by tvandera** [comment]
Related to this, if I run `./smurff` withouth any options I get a segfault. Previously it was correctly saying that `--train` is required.

Segfault here:

https://github.com/ExaScience/smurff/blob/master/lib/smurff-cpp/SmurffCpp/Configs/Config.cpp#L85

because `m_train == 0`
