### ISSUE TITLE
Unused command line arguments

### ISSUE THREAD

**Issue by motoharu-yano** [ExaScience/smurff#64]
We have these arguments. They are not parsed. Do we need them?
{"row-model",        FNAME_ROW_MODEL	, "FILE",  0, "initialization matrix for row model"},
{"col-model",        FNAME_COL_MODEL	, "FILE",  0, "initialization matrix for col model"},

**Comment by tvandera** [comment]
If they're not used, that seems like a bug

**Comment by ipasechnikov** [comment]
We have skimmed though `cmd_session.cpp` file history and it seems that these options have never been implemented. First time they were introduced here 9ad5a2521e0fbe62bd6ed697780b39f2bcae7ce0.

**Comment by tvandera** [comment]
Indeed. Probably superseded by `--restore-suffix`

**Comment by tvandera** [comment]
To be removed.
