### ISSUE TITLE
Remove legacy code coming from jaak-s/macau

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#72]
- https://github.com/ExaScience/smurff/blob/master/lib/macau-cpp/
- Various comment sections
  - e.g. GlobalPrior.cpp and MacauOnePrior.cpp
- https://github.com/ExaScience/smurff/tree/master/python/macau/

**Comment by motoharu-yano** [comment]
Fix or remove this?
https://github.com/ExaScience/smurff/blob/master/Dockerfile

Remove this?
https://github.com/ExaScience/smurff/blob/master/.vimrc

Remove this?
https://github.com/ExaScience/smurff/blob/master/MANIFEST.in

Remove this?
https://github.com/ExaScience/smurff/blob/master/.gitmodules

**Comment by tvandera** [comment]
* `Dockerfile`: update
* `.vimrc`: remove
* `MANIFEST.in`: move to python/smurff and update
* `.gitmodules`: remove

**Comment by ipasechnikov** [comment]
As far as I am concerned, `MANIFEST.in` is outdated and mostly used for python 2. It is used to include non source code resources. I suppose you can use `setup.py` instead if you really need to include such kind of resources. It's safe to not provide `MANIFEST.in` if you don't need one. Currently everything works with just `setup.py`. So we can remove `MANIFEST.in`.

**Comment by tvandera** [comment]
Let's then remove MANIFEST.in
