### ISSUE TITLE
start modeling from ini file

### ISSUE THREAD

**Issue by chupvl** [ExaScience/smurff#78]
it would ease significantly if you can provide .ini file for modeling instead of providing parameters in a command line.

**Comment by tvandera** [comment]
ini file should have the least info needed

**Comment by tvandera** [comment]
Implemented as of 1fa922bd90e8a0a1db929693c9460acf1115354c,
still need to have better defaults.

**Comment by motoharu-yano** [comment]
@tvandera 
We already have a possibility to start smurff execution with --ini option.
Or continue smurff execution with --root option.
We already have some defaults in Config::Config() and Config::restore().
Previously there were also defaults in CmdSession parser.
Lets discuss during next call what defaults do we need.

**Comment by tvandera** [comment]
Re-added boost default options, to make them show up in --help. (Still to be committed).
Let's put defaults as static members in Config class, and use them in Config::restore and CmdSession.cpp.
