### ISSUE TITLE
iteration n-1 is saved

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#82]
instead of iteration n

**Comment by tvandera** [comment]
also if you may please check with save-freq=1 since it seems to save also during burnin phase

**Comment by motoharu-yano** [comment]
@tvandera 
Not sure how it worked previously but it looks like to be working properly in improve-restore branch.
With both save-freq=1 and any other value for save-freq.
There was a bug though where last burnin iteration was considered as first sampling iteration.
Anyhow - it would be great if you could double check this on your side with improve-restore branch.
