### ISSUE TITLE
Duplicate records in .mtx files

### ISSUE THREAD

**Issue by motoharu-yano** [ExaScience/smurff#83]
While testing the code I have encountered the following situation.
In one of .mtx files there were duplicate records featuring same row and column in the matrix but having different value. Our parser does not take this into account at the moment and we may get multiple assertions failing. Here is one example:
https://github.com/ExaScience/smurff/blob/master/lib/smurff-cpp/SmurffCpp/Utils/MatrixUtils.cpp#L68
Matrix config contains one NNZ value which counts duplicated records.
Upon converting it to Eigen::SparseMatrix<double> records get deduplicated and assertion fails.
How we should handle duplicates?

**Comment by tvandera** [comment]
I would keep the assertion. 
Eigen sums all values, so that's also an option.

**Comment by motoharu-yano** [comment]
@tvandera 
Assertion is good. However we only get it when conversion function like sparse_to_eigen is used.
Before that moment MatrixConfig technically has invalid state. Is this ok?

**Comment by tvandera** [comment]
- Add filename in error message
