### ISSUE TITLE
Documentation for SMURFF

### ISSUE THREAD

**Issue by golipe** [ExaScience/smurff#84]
Use the documentation at (http://jaak-s.github.io/BayesianDataFusion.jl/) as a template and create a SMURFF version of the examples. Unlike the template documentation, the smurff documentation should use ExCAPE data.

**Comment by tvandera** [comment]
Or start from http://macau.readthedocs.io/en/latest/source/examples.html and convert it to IPython notebook.

**Comment by tvandera** [comment]
Put ExCAPE data on Google Drive.

**Comment by ipasechnikov** [comment]
Initial documentation is available in [`jupyter-notebook`](https://github.com/ExaScience/smurff/tree/jupyter-notebook) branch.
https://github.com/ExaScience/smurff/blob/jupyter-notebook/python/jupyter-notebook/smurff.ipynb

Still need to fix C++ verbose console output to show up in jupyter notebook.

**Comment by ipasechnikov** [comment]
Fixing C++ verbose console output doesn't seem to be an easy task.
Python uses `sys.stdout` for functions like `print`. By default `sys.stdout` is a system `stdout` stream wrapper. When you run jupyter it sets `sys.stdout` to its own stream class `OutStream`. But C++ side doesn't know anything about `sys.stdout` stream that it has changed, it continues to use system `stdout` stream that has no relation to jupyter.
Also it doesn't seem that you can create pipe between these two streams, cause `OutStream` has no file descriptor.

**Comment by tvandera** [comment]
Documentation on http://smurff.readthedocs.io
