### ISSUE TITLE
Noise model and matrix type via ini file

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#88]
noise model per aux-data
scarce/sparse per aux-data

**Comment by tvandera** [comment]
Implemented since ed4ee0106dc8b45e4f68e8f3bc102e62160bc5d7
Still untested

**Comment by motoharu-yano** [comment]
I made further improvements and fixed couple of minor bugs in c193cfc2c135f03f8b34a3280f2b5ab84ca42cac
Save/Restore functionality is working as expected.
I assume that start from ini file should also work (same functionality under the hood).

**Comment by tvandera** [comment]
Python interface still to be updated

**Comment by ipasechnikov** [comment]
Added `ini_path` parameter to Python interface. Implemented in commit 82499d84a27e5e89756fb6ca3c60a67bbbca374a.
