### ISSUE TITLE
none none as default for --side-info and --aux-data

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#89]
in cmd line smurff

**Comment by tvandera** [comment]
Done as of f8dfed1469443188567c89735a183940e81221de

**Comment by tvandera** [comment]
@ipasechnikov: can you do the same for python?

**Comment by ipasechnikov** [comment]
Implemeted in commit e05494caec132c96d7fb81ffb146c1ba689a6289 of [`juptyter-notebook`](https://github.com/ExaScience/smurff/tree/jupyter-notebook) branch. I will merge `master` into it a bit later.

**Comment by ipasechnikov** [comment]
`jupyter-notebook` branch is now merge into `master` branch. Everything compiles and all [tests](https://github.com/ExaScience/smurff/tree/master/python/smurff/test) pass. Commit 68e63b22630705d1cba92dbef599092cf5d49205.
