### ISSUE TITLE
Add linux makefile

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#9]
and test it

**Comment by tvandera** [comment]
Also: We need to have some checks to verify that openblas path is correct.

**Comment by ipasechnikov** [comment]
As far as I am concerned, we don't need to verify openblas path on Linux. Cause if you have openblas installed in your system then linker will be able to figure out openblas location.

**Comment by ipasechnikov** [comment]
[Makefile for Linux](https://github.com/ExaScience/smurff/blob/smurff/lib/smurff-cpp/makefiles/linux/Makefile) was added and tested on 2 virtual machines with Ubuntu 16.04.3 LTS installed. So everything should be fine with Ubuntu at least. All changes are in smurff branch now.

**Comment by tvandera** [comment]
Let's also add a Makefile using openmp

`CXXFLAGS+=-fopenmp`

**Comment by ipasechnikov** [comment]
We have updated Makefile.common and included it in all linux makefiles, same as it is done for mac makefiles.

Both linux makefiles were tested, they work fine. Even mac makefiles are pretty much usable on linux. There should be no problem with mac, but still could you please compile smurff on mac, just to make sure that everything is ok for mac too, that nothing is wrong with `Makefile.common` and it works on mac too.

827c6ad9388b1919d65217b463f64a9ddb6013ef - commit with all these changes.
