### ISSUE TITLE
aux-data for >2 dimensions

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#97]
This code:

https://github.com/ExaScience/smurff/blob/d395b1852b9c792c1ff77cd15be29d00f0f8e2b7/lib/smurff-cpp/SmurffCpp/Sessions/CmdSession.cpp#L221-L223

* Parse correctly if more than 2 dimensions, but
* complain when we have more than 2 dimensions later

**Comment by motoharu-yano** [comment]
Fixed in https://github.com/ExaScience/smurff/commit/4bc6c38266c5814d4b7445205faf5b2f680dc15c
